packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@prisma/engines'
  - electron
  - esbuild
  - fs-xattr
  - macos-alias
  - msw
  - prisma
  - protobufjs
  - sharp

patchedDependencies:
  '@auth/prisma-adapter': patches/@auth__prisma-adapter.patch
