packages:
  - 'apps/*'

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp

patchedDependencies:
  '@auth/prisma-adapter': patches/@auth__prisma-adapter.patch
