import { BrowserWindow, ipcMain } from "electron";
import { type ChildProcess, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import log from "electron-log/main";

type Session = { proc: ChildProcess; cwd: string };

const sessions = new Map<string, Session>();

function emit(payload: Record<string, unknown>): void {
  for (const w of BrowserWindow.getAllWindows())
    w.webContents.send("planbooq:agent:event", payload);
}

function isSafeBranch(s: string): boolean {
  return /^[A-Za-z0-9._/\-]{1,200}$/.test(s) && !s.includes("..");
}

type TicketContext = {
  ticketId: string;
  identifier: string;
  title: string;
  apiBaseUrl: string;
  apiToken: string;
};

async function writeTicketContext(wtPath: string, ctx: TicketContext): Promise<void> {
  const dir = path.join(wtPath, ".planbooq");
  await fs.mkdir(dir, { recursive: true });

  // Generic wrapper — no secrets on disk. Reads PLANBOOQ_API / PLANBOOQ_TOKEN /
  // PLANBOOQ_TICKET_ID from the process env, which the desktop app injects when
  // it spawns claude. Same script for every ticket.
  const script = `#!/bin/sh
# Auto-generated by Planbooq desktop app. Reads creds from the environment;
# the desktop app sets PLANBOOQ_API, PLANBOOQ_TOKEN, and PLANBOOQ_TICKET_ID
# when it spawns Claude Code. If you see "missing env" below, the session was
# started outside Planbooq.

: "\${PLANBOOQ_API:?missing env: PLANBOOQ_API (start this session from Planbooq)}"
: "\${PLANBOOQ_TOKEN:?missing env: PLANBOOQ_TOKEN}"
: "\${PLANBOOQ_TICKET_ID:?missing env: PLANBOOQ_TICKET_ID}"

usage() {
  cat <<EOF
Planbooq REST wrapper · ticket ${ctx.identifier} (\${PLANBOOQ_TICKET_ID})
Usage:
  ./.planbooq/pbq get
  ./.planbooq/pbq update '{"description":"..."}'   # PATCH this ticket
  ./.planbooq/pbq comment '{"body":"..."}'         # add a comment
  ./.planbooq/pbq raw <METHOD> <path-after-/api/v1> [json]
Fields accepted by 'update': title, description, statusId, priority, assigneeId, dueAt
EOF
}

[ $# -lt 1 ] && { usage; exit 1; }
cmd="$1"; shift
H_AUTH="Authorization: Bearer $PLANBOOQ_TOKEN"
H_JSON="Content-Type: application/json"

case "$cmd" in
  get)
    curl -sS -H "$H_AUTH" "$PLANBOOQ_API/api/v1/tickets/$PLANBOOQ_TICKET_ID"
    ;;
  update)
    [ -z "$1" ] && { echo "missing JSON body" >&2; exit 2; }
    curl -sS -X PATCH -H "$H_AUTH" -H "$H_JSON" -d "$1" \\
      "$PLANBOOQ_API/api/v1/tickets/$PLANBOOQ_TICKET_ID"
    ;;
  comment)
    [ -z "$1" ] && { echo "missing JSON body" >&2; exit 2; }
    curl -sS -X POST -H "$H_AUTH" -H "$H_JSON" -d "$1" \\
      "$PLANBOOQ_API/api/v1/tickets/$PLANBOOQ_TICKET_ID/comments"
    ;;
  raw)
    method="$1"; subpath="$2"; data="$3"
    [ -z "$method" ] || [ -z "$subpath" ] && { echo "raw <METHOD> <path> [json]" >&2; exit 2; }
    if [ -n "$data" ]; then
      curl -sS -X "$method" -H "$H_AUTH" -H "$H_JSON" -d "$data" \\
        "$PLANBOOQ_API/api/v1/$subpath"
    else
      curl -sS -X "$method" -H "$H_AUTH" "$PLANBOOQ_API/api/v1/$subpath"
    fi
    ;;
  *) usage; exit 2 ;;
esac
`;
  const scriptPath = path.join(dir, "pbq");
  await fs.writeFile(scriptPath, script, { mode: 0o700 });
  await fs.chmod(scriptPath, 0o700);

  const claudeMd = `<!-- Auto-generated by Planbooq. Do not edit; regenerated each session. -->
# Planbooq ticket context

You are working on Planbooq ticket **${ctx.identifier}** — "${ctx.title.replace(/"/g, '\\"')}".

When the user says "the ticket", "this ticket", or refers to a ticket without
naming one, they mean **${ctx.identifier}** (id: \`${ctx.ticketId}\`).

Use \`./.planbooq/pbq\` to read or mutate it via the Planbooq REST API:

- \`./.planbooq/pbq get\` — fetch the current ticket
- \`./.planbooq/pbq update '{"description":"..."}'\` — PATCH fields
  (title, description, statusId, priority, assigneeId, dueAt)
- \`./.planbooq/pbq comment '{"body":"..."}'\` — post a comment
- \`./.planbooq/pbq raw GET tickets\` — generic call (path is appended to /api/v1/)

The wrapper hard-codes the ticket id, base URL, and a 7-day API token, so you
do not need to supply credentials. Prefer it over hand-rolling curl. Do not
echo or log the contents of \`./.planbooq/pbq\`.
`;
  // Write as CLAUDE.local.md so we don't clobber a project's CLAUDE.md.
  await fs.writeFile(path.join(wtPath, "CLAUDE.local.md"), claudeMd);
}

async function isGitRepo(p: string): Promise<boolean> {
  try {
    const stat = await fs.stat(path.join(p, ".git"));
    return stat.isDirectory() || stat.isFile();
  } catch {
    return false;
  }
}

function runOnce(cmd: string, args: string[], cwd: string, sessionId: string): Promise<number> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { cwd, env: process.env, stdio: ["ignore", "pipe", "pipe"] });
    proc.stdout?.on("data", (b: Buffer) =>
      emit({ type: "stderr", sessionId, line: b.toString() }),
    );
    proc.stderr?.on("data", (b: Buffer) =>
      emit({ type: "stderr", sessionId, line: b.toString() }),
    );
    proc.on("error", reject);
    proc.on("exit", (code) => resolve(code ?? 0));
  });
}

function userMessage(text: string): string {
  return `${JSON.stringify({
    type: "user",
    message: { role: "user", content: text },
  })}\n`;
}

function spawnClaude(
  cwd: string,
  sessionId: string,
  opts: { resumeId?: string; ticket?: TicketContext } = {},
): ChildProcess {
  const args = [
    "--print",
    "--input-format",
    "stream-json",
    "--output-format",
    "stream-json",
    "--include-partial-messages",
    "--verbose",
  ];
  if (opts.resumeId) args.push("--resume", opts.resumeId);
  const env: NodeJS.ProcessEnv = { ...process.env };
  if (opts.ticket) {
    env.PLANBOOQ_API = opts.ticket.apiBaseUrl;
    env.PLANBOOQ_TOKEN = opts.ticket.apiToken;
    env.PLANBOOQ_TICKET_ID = opts.ticket.ticketId;
  }
  const proc = spawn("claude", args, {
    cwd,
    env,
    stdio: ["pipe", "pipe", "pipe"],
  });

  let buffer = "";
  proc.stdout?.on("data", (b: Buffer) => {
    buffer += b.toString();
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      if (!line.trim()) continue;
      emit({ type: "agent", sessionId, line });
    }
  });
  proc.stderr?.on("data", (b: Buffer) =>
    emit({ type: "stderr", sessionId, line: b.toString() }),
  );
  proc.on("error", (err) => {
    log.error("claude spawn error", err);
    emit({ type: "stderr", sessionId, line: `[spawn error] ${err.message}\n` });
  });
  proc.on("exit", (code) => {
    sessions.delete(sessionId);
    emit({ type: "exit", sessionId, code: code ?? 0 });
  });
  return proc;
}

export function registerAgentIpc(): void {
  ipcMain.handle(
    "planbooq:agent:start",
    async (
      _,
      input: {
        repoPath: string;
        branch: string;
        firstMessage: string;
        ticket?: TicketContext;
      },
    ) => {
      if (!input?.repoPath || !input?.branch || !input?.firstMessage)
        return { ok: false, error: "missing fields" };
      if (!isSafeBranch(input.branch)) return { ok: false, error: "invalid branch" };
      if (!(await isGitRepo(input.repoPath))) return { ok: false, error: "not a git repo" };

      const sessionId = randomUUID();
      const ts = new Date().toISOString().replace(/[^0-9]/g, "").slice(0, 14);
      const wtName = `${path.basename(input.repoPath)}.planbooq-${ts}`;
      const wtPath = path.join(path.dirname(input.repoPath), wtName);

      emit({ type: "stderr", sessionId, line: `$ git worktree add -b ${input.branch} ${wtPath}\n` });
      const code = await runOnce(
        "git",
        ["worktree", "add", "-b", input.branch, wtPath],
        input.repoPath,
        sessionId,
      );
      if (code !== 0) return { ok: false, error: `git worktree add exited ${code}` };

      if (input.ticket) {
        try {
          await writeTicketContext(wtPath, input.ticket);
        } catch (err) {
          log.warn("writeTicketContext failed", err);
          emit({
            type: "stderr",
            sessionId,
            line: `[planbooq] could not write ticket context: ${err instanceof Error ? err.message : String(err)}\n`,
          });
        }
      }

      const proc = spawnClaude(wtPath, sessionId, { ticket: input.ticket });
      sessions.set(sessionId, { proc, cwd: wtPath });
      proc.stdin?.write(userMessage(input.firstMessage));

      return { ok: true, sessionId, worktreePath: wtPath };
    },
  );

  ipcMain.handle(
    "planbooq:agent:resume",
    async (
      _,
      input: {
        worktreePath: string;
        claudeSessionId: string;
        message: string;
        ticket?: TicketContext;
      },
    ) => {
      if (!input?.worktreePath || !input?.claudeSessionId || !input?.message)
        return { ok: false, error: "missing fields" };
      if (!(await isGitRepo(input.worktreePath)))
        return { ok: false, error: "worktree no longer exists" };

      const sessionId = randomUUID();
      const proc = spawnClaude(input.worktreePath, sessionId, {
        resumeId: input.claudeSessionId,
        ticket: input.ticket,
      });
      sessions.set(sessionId, { proc, cwd: input.worktreePath });
      proc.stdin?.write(userMessage(input.message));
      return { ok: true, sessionId };
    },
  );

  ipcMain.handle(
    "planbooq:agent:send",
    async (_, input: { sessionId: string; message: string }) => {
      const s = sessions.get(input.sessionId);
      if (!s) return { ok: false, error: "session not found" };
      s.proc.stdin?.write(userMessage(input.message));
      return { ok: true };
    },
  );

  ipcMain.handle("planbooq:agent:stop", async (_, input: { sessionId: string }) => {
    const s = sessions.get(input.sessionId);
    if (!s) return { ok: false, error: "session not found" };
    s.proc.kill();
    sessions.delete(input.sessionId);
    return { ok: true };
  });
}
